config/routes.rb
AbilityMatrimony::Application.routes.draw do
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :microposts, only: [:create, :destroy]
    resources :password_resets
    
    root to: 'static_pages#home'
    match '/home',    to: 'static_pages#home'
    match '/help',    to: 'static_pages#help'
    match '/about',   to: 'static_pages#about'
    match '/contact', to: 'static_pages#contact'
    match '/galleries', to: 'static_pages#galleries'
    match '/signup',  to: 'users#new'
    match '/signin',  to: 'sessions#new'
    match '/signout', to: 'sessions#destroy', via: :delete
    match '/partners', to: 'static_pages#partners'
    match '/10poruthams', to: 'static_pages#poruthams'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="#">&copy;2013 Shree Geeta Bhavan Trust</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Developer", 'https://twitter.com/karthy07', :target => '_blank' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div id="mynav" class="navbar">
   <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <nav>
            <ul class="nav">
              <li><%= link_to "Home",    root_path %></li>
              <li><%= link_to "About Us",    about_path %></li>
              <li><%= link_to "Contact", contact_path %></li>
              <li><%= link_to "Help", help_path %></li>
              <li><%= link_to "Our Partners", partners_path %></li>
              
            </ul>

            <ul class="nav pull-right">
              <% if signed_in? %>
            	<li>
            		<!-- > -->
  					     <div class="pull-right">
                    <form class="navbar-search pull-right" action = "/search"        method="get" >
                      <input type="text" name = "search"  class="search-query" placeholder="Search">
                    </form>
					       </div>
  				    </li>

					<li class="dropdown pull-right">
   						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
   							Account<b class="caret"></b>
   						</a>
   	 		    		<ul class="dropdown-menu">
   	 		    			<li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Gallery", galleries_path %></li>
 			    			<li><%= link_to "Settings", edit_user_path(current_user) %></li>
 			    			<li><%= link_to "Users", users_path %></li>
							<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
   						</ul>
   			    <% else %>
   			    	<li><%= link_to "Sign in", signin_path %></li>
   		  		<% end %>
			</ul>
          </nav>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <link href="/maps/documentation/javascript/examples/default.css" rel="stylesheet">
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"></script>
  <%= render 'layouts/shim' %>
  <script src="/javascript/java.js" type="text/javascript"></script>
</head>
<body>
	<header class="lg1">
		<div class="container-fluid">
			<div class="row-fluid">
				<div id="lg2" class="span12">
					<h1><%= image_tag("image.png", :size => "64x64", :alt => "Show Group") %>
          Ability Matrimony ! India's 1st Matrimony for differently abled</h1>
				</div>
        <div class="row-fluid">
          <div class="span4 offset8">
            <small>sponsored by <%= full_title('') %></small>
          </div>
        </div>
        
			</div>
		</div>
	</header>
	<div class="container-fluid">
		<%= render 'layouts/header'%>
	</div>

	<div class="container">
		<% flash.each do |key, value| %>
      	  <div class="alert alert-<%= key %>"><%= value %></div>
      	<% end %>
      <%= yield %>
    </div>
    <div class="container-fluid">
    	<%= render 'layouts/footer' %>
    	<!-- <%= debug(params) if Rails.env.development? %> -->
    </div>
    <script>
    $('.dropdown-toggle').dropdown();
    </script>
</body>
</html>